# Generated by Django 2.2.6 on 2020-06-21 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymovies', '0002_auto_20200621_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='movie_id',
            new_name='movie',
        ),
    ]
